USE [DB_DISPEL]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[SP_ExcluirPedido]  
	@IdPedido int	
AS
BEGIN
	Update Pedido Set DATaHORaEXCLUIDO = GETUTCDATE(), SITUACAO = 'I' 	Where IdPEDIDO = @IdPedido 
	Update ItemPedido Set SITUACAO = 'I' Where IdPEDIDO = @IdPedido 

	IF OBJECT_ID('tempdb..#TempItemPedido') IS NOT NULL 
		DROP TABLE #TempItemPedido

	CREATE TABLE #TempItemPedido (REFERENCIA varchar(50), QUANTIDADE int)

	Insert Into #TempItemPedido
		SELECT IdREFERENCIA, QUANTIDADE FROM ITEMPEDIDO WHERE IDPEDIDO = @IdPedido

	UPDATE e SET
		e.QUANTIDADE = e.QUANTIDADE + t.QUANTIDADE
	FROM 
		Estoque e
	INNER JOIN 
		#TempItemPedido t ON t.REFERENCIA = e.IdREFESTOQUE
	WHERE 
		IdREFESTOQUE IN (Select REFERENCIA FROM #TempItemPedido) 
END
GO