USE [DB_GESTORIX]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[SP_SelecionarItensPedido]
	@IdPedido int
AS
BEGIN
	Select IdPEDIDO,IdREFERENCIA,TIPoITEM,DESCRICAO,CUSTO,PRECO,LUCRO,QUANTIDADE From ItemPedido Where IdPEDIDO = @IdPedido
END
GO