USE [DB_GESTORIX]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[SP_ListarProdutos]  

AS
BEGIN
	SELECT IdREFPRODUTO, TIPO, DESCRICAO, FABRICANTE, CUSTO, PRECO FROM DB_GESTORIX..Produto WHERE SITUACAO = 'A'
END
GO