USE [DB_DISPEL]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
  
CREATE PROCEDURE [dbo].[SP_SelecionarProduto]
 @ReferenciaProduto varchar(50)
AS  
BEGIN  
 SELECT IdREFPRODUTO,TIPO,DESCRICAO,FABRICANTE,CUSTO,PRECO, QUANTIDADE FROM Produto JOIN Estoque ON IdREFESTOQUE = IdREFPRODUTO WHERE IdREFPRODUTO = @ReferenciaProduto AND Produto.SITUACAO = 'A'
END